//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STAFF_REGISTER_DT
    {
        public long ID { get; set; }
        public long STAFF_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<decimal> PAYMENT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        public virtual TBL_STAFF_REGISTER TBL_STAFF_REGISTER { get; set; }
    }
}
