//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OWN_CYLINDER_REGISTER
    {
        public long ID { get; set; }
        public long CYLINDR_TYPE_ID { get; set; }
        public string NUMBER { get; set; }
        public System.DateTime PURCHASE_DATE { get; set; }
        public System.DateTime LAST_TEST_DATE { get; set; }
        public System.DateTime NEXT_TEST_DATE { get; set; }
        public Nullable<int> SALED_TO { get; set; }
        public Nullable<System.DateTime> SALED_DATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        public virtual TBL_CYLINDER_MASTER TBL_CYLINDER_MASTER { get; set; }
    }
}
