//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CYLINDER_MASTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CYLINDER_MASTER()
        {
            this.TBL_CYLINDER_TRACKING = new HashSet<TBL_CYLINDER_TRACKING>();
            this.TBL_OWN_CYLINDER_REGISTER = new HashSet<TBL_OWN_CYLINDER_REGISTER>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public string CYLINDER_SHORT_NAME { get; set; }
        public string HSN_CODE { get; set; }
        public Nullable<int> RENT_DAYS_SLAB1 { get; set; }
        public Nullable<int> RENT_DAYS_SLAB2 { get; set; }
        public Nullable<decimal> SELLING_AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CYLINDER_TRACKING> TBL_CYLINDER_TRACKING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OWN_CYLINDER_REGISTER> TBL_OWN_CYLINDER_REGISTER { get; set; }
    }
}
