//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PURCHASE_INVOICE_DT
    {
        public long ID { get; set; }
        public long PURCHASE_ID { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public string HSN_CODE { get; set; }
        public int TOTAL_CYLNIDER { get; set; }
        public decimal QUATITY { get; set; }
        public decimal RATE { get; set; }
        public Nullable<decimal> PURCHASE_AMOUNT { get; set; }
        public Nullable<decimal> HANDLING_AMOUNT { get; set; }
        public decimal TOTAL_AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        public virtual TBL_PURCHASE_HD TBL_PURCHASE_HD { get; set; }
    }
}
