//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_VECHICLE_REGISTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_VECHICLE_REGISTER()
        {
            this.TBL_PURCHASE_HD = new HashSet<TBL_PURCHASE_HD>();
            this.TBL_SALE_HD = new HashSet<TBL_SALE_HD>();
            this.TBL_VECHICLE_REGISTER_DT = new HashSet<TBL_VECHICLE_REGISTER_DT>();
        }
    
        public long ID { get; set; }
        public string NUMBER { get; set; }
        public Nullable<System.DateTime> PURCHASE_DATE { get; set; }
        public Nullable<System.DateTime> TEST_DATE { get; set; }
        public Nullable<System.DateTime> INSURANCE_DATE { get; set; }
        public Nullable<System.DateTime> TAX_DATE { get; set; }
        public Nullable<System.DateTime> POLUTION_DATE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PURCHASE_HD> TBL_PURCHASE_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SALE_HD> TBL_SALE_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_VECHICLE_REGISTER_DT> TBL_VECHICLE_REGISTER_DT { get; set; }
    }
}
