//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEALER_PAYMENT_HD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DEALER_PAYMENT_HD()
        {
            this.TBL_DEALER_PAYMENT_DT = new HashSet<TBL_DEALER_PAYMENT_DT>();
        }
    
        public long ID { get; set; }
        public long DEALER_ID { get; set; }
        public Nullable<decimal> OUTSTANDING_PURCHASE_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_RENT_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_HANDLING_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_VECHICLE_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_OTHER_AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DEALER_PAYMENT_DT> TBL_DEALER_PAYMENT_DT { get; set; }
        public virtual TBL_SHOP_DEALER_REGISTER TBL_SHOP_DEALER_REGISTER { get; set; }
    }
}
