//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SHOP_DEALER_BANK_DETAILS
    {
        public long ID { get; set; }
        public Nullable<long> SHOP_DEALER_ID { get; set; }
        public string HOLDER { get; set; }
        public string BANK_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string AC_NUMBER { get; set; }
        public string IFSC { get; set; }
        public string DEFAULT { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    }
}
