//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMER_PAYMENT_HD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CUSTOMER_PAYMENT_HD()
        {
            this.TBL_CUSTOMER_PAYMENT_DT = new HashSet<TBL_CUSTOMER_PAYMENT_DT>();
        }
    
        public long ID { get; set; }
        public long CUSTOMER_ID { get; set; }
        public Nullable<decimal> OUTSTANDING_PURCHASE_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_RENT_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_HANDLING_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_VECHICLE_AMOUNT { get; set; }
        public Nullable<decimal> OUTSTANDING_OTHER_AMOUNT { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CUSTOMER_PAYMENT_DT> TBL_CUSTOMER_PAYMENT_DT { get; set; }
        public virtual TBL_CUSTOMER_REGISTER TBL_CUSTOMER_REGISTER { get; set; }
    }
}
