//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMER_REGISTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CUSTOMER_REGISTER()
        {
            this.TBL_CUSTOMER_PAYMENT_HD = new HashSet<TBL_CUSTOMER_PAYMENT_HD>();
            this.TBL_SALE_HD = new HashSet<TBL_SALE_HD>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public string MOB1 { get; set; }
        public string MOB2 { get; set; }
        public string EMAIL_ID { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<decimal> DEPOSITE { get; set; }
        public Nullable<int> AGREEMENT_BILL_NUMER { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> REGISTER_DATE { get; set; }
        public Nullable<bool> IS_FLOW_METER_SALED { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public Nullable<decimal> DEPOSITE_RETURENED_AMOUNT { get; set; }
        public string MODE { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CUSTOMER_PAYMENT_HD> TBL_CUSTOMER_PAYMENT_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SALE_HD> TBL_SALE_HD { get; set; }
    }
}
