//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QconzLocateDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SHOP_DEALER_REGISTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SHOP_DEALER_REGISTER()
        {
            this.TBL_DEALER_PAYMENT_HD = new HashSet<TBL_DEALER_PAYMENT_HD>();
            this.TBL_PURCHASE_HD = new HashSet<TBL_PURCHASE_HD>();
        }
    
        public long ID { get; set; }
        public string NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string MOB1 { get; set; }
        public string MOB2 { get; set; }
        public string EMAIL { get; set; }
        public string GST_NUM { get; set; }
        public string M_LICENCE_NUM1 { get; set; }
        public string M_LICENCE_NUM2 { get; set; }
        public string D_LICENCE_NUM { get; set; }
        public string E_LICENCE_NUM { get; set; }
        public string REMARKS { get; set; }
        public string SHOP_OR_DEALER { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DEALER_PAYMENT_HD> TBL_DEALER_PAYMENT_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PURCHASE_HD> TBL_PURCHASE_HD { get; set; }
    }
}
